version: "3.1"
services:
  mongo:
    image: quevotan-mongodb
    container_name: quevotan-mongodb
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: wfp6UL9eeSNN9ngb
    ports:
      - 27018:27017
    networks:
      - quevotannetwork
      
networks:
  quevotannetwork:
    name: quevotannetwork
