version: "3.1"
services:
  mongo:
    image: mongo:5.0.5
    container_name: quevotan-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: wfp6UL9eeSNN9ngb
    ports:
      - 27018:27017
